### ISSUE TITLE
Wish: Ability to change capability for the "Webhook Deploy" admin page

### ISSUE THREAD

**Issue by kimhornung** [lukethacoder/wp-webhook-netlify-deploy#10]
Use case: I have a project where I would like to allow users with the "editor" role to see the "Webhook Deploy" admin page and to trigger the "Build Site" command. 

For this purpose, it would be useful if I as a develop could hook into a filter that changed the $capability variable in the `create_plugin_settings_page()` function.

In other words, adding something along the following lines in the function:
```php
$capability = apply_filters( 'deploy_webhook_menu_capability', 'manage_options' );
```

With that in place, I would be able to override the capabilities with a filter:
```php
add_filter( 'deploy_webhook_menu_capability', 'override_deploy_webhook_capability' );
function override_deploy_webhook_capability( $capability ) {
  return 'edit_others_pages';
}
```

Thanks :-)

**Comment by lukethacoder** [comment]
Great idea @kimhornung. Unfortunately I don't currently have capacity to be working on this plugin at the moment.

Feel free to create a PR with this feature implemented. More than happy to assist if needed

**Comment by lukethacoder** [comment]
Big thanks to @marijoo for creating a PR implementing this feature #11 
Hopefully be merging and pushing into MASTER in the next day or two

**Comment by lukethacoder** [comment]
Updated the plugin with basic user roles. 

Closing this for now in favour of #7 (which should help solve this issue).

But would still love if someone could lend a hand with a proper JavaScript overhaul, to allow for dynamically pulling in only what is needed based on user permissions (can see deploy / can deploy / can edit settings) and where the user is (non-settings page only needs admin bar js).

**Comment by kimhornung** [comment]
Thanks a lot! Might have a look to see if I can help with the JavaScript overhaul at some point.
