### ISSUE TITLE
Nightly/Weekly Build - WordPress Cron

### ISSUE THREAD

**Issue by robmarshall** [lukethacoder/wp-webhook-netlify-deploy#13]
I am working on a WordPress -> Gatsby site that has events, and needs re-building nightly to update which events have finished/are about to happen. I was going to create a custom plugin but found your build.

How would you feel about me adding an option that allows the user to set automatic builds based off times/schedules via the WordPress cron?

Cheers,
Rob

**Comment by lukethacoder** [comment]
@robmarshall sounds like a great idea.

Adding another sub page under the plugin settings would be perfect.

Feel free to open a PR, or give us a yell if you need a hand with anything.

**Comment by robmarshall** [comment]
Nice one.

**Comment by robmarshall** [comment]
Are you able to explain how the checkbox/select input type generator works? Cannot get my head around it?

I'll add some dev notes in the code once you have. 

Thanks

**Comment by robmarshall** [comment]
No worries - found it https://www.smashingmagazine.com/2016/04/three-approaches-to-adding-configurable-fields-to-your-plugin/

**Comment by lukethacoder** [comment]
added functionality with #14
