### ISSUE TITLE
Preview builds

### ISSUE THREAD

**Issue by dustinhorton** [lukethacoder/wp-webhook-netlify-deploy#2]
Nice work—any plans to support preview builds?

**Comment by HurricaneInteractive** [comment]
@dustinhorton I'll look into it. At the moment I am going to make the current experience a bit more like Netlify, in terms of seeing your deployment status in "real-time" before moving onto other features. I'll keep it in mind!

**Comment by lukethacoder** [comment]
@dustinhorton @HurricaneInteractive It would be awesome to have that build console preview built into the plugin. unfortunately I don't think it is natively/currently supported. I am sure it is possible

**Comment by lukethacoder** [comment]
Closing as preview builds (in the form of an in-plugin iframe) has been built in with future plans for live console builds
